name: accessibility_keynote
description: Code for the live demo for my accessibility keynote.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0-340.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  video_player: ^2.4.7
  qr_flutter: ^4.0.0
  go_router: ^5.1.5
  rive: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
